-- ============================================================================
-- QUERY 04: RFM (RECENCY, FREQUENCY, MONETARY) CUSTOMER SEGMENTATION
-- Business Question:
-- "How do we classify customers into actionable behavioral segments (Champions, Loyalists, 
--  At-Risk, Lost) based on Recency, Frequency, and Monetary scores, and what is the revenue 
--  and profit distribution across these segments?"
-- Multi-step explicit CTE chain for executive clarity and interview defense.
-- ============================================================================

-- Step 1: Extract baseline RFM raw metrics per customer
WITH rfm_raw AS (
    SELECT 
        c.customer_id,
        c.first_name || ' ' || c.last_name AS customer_name,
        c.region,
        c.customer_segment AS original_tier,
        
        -- Recency: Days between last order date and dataset max date ('2025-12-31')
        CAST(JULIANDAY('2025-12-31') - JULIANDAY(MAX(o.order_date)) AS INT) AS recency_days,
        
        -- Frequency: Total completed orders placed by customer
        COUNT(DISTINCT o.order_id) AS frequency_orders,
        
        -- Monetary: Total net revenue generated by customer
        ROUND(SUM((oi.quantity * oi.unit_price) * (1.0 - oi.discount_percent)), 2) AS monetary_net_revenue,
        
        -- Total Net Profit generated by customer
        ROUND(SUM((((oi.quantity * oi.unit_price) * (1.0 - oi.discount_percent)) - (oi.quantity * p.unit_cost))), 2) AS monetary_net_profit

    FROM customers c
    JOIN orders o ON c.customer_id = o.customer_id
    JOIN order_items oi ON o.order_id = oi.order_id
    JOIN products p ON oi.product_id = p.product_id
    WHERE o.order_status = 'Completed'
    GROUP BY c.customer_id, customer_name, c.region, c.customer_segment
),

-- Step 2: Assign NTILE(4) quartile scores (4 is best, 1 is worst)
rfm_quartiles AS (
    SELECT 
        customer_id,
        customer_name,
        region,
        original_tier,
        recency_days,
        frequency_orders,
        monetary_net_revenue,
        monetary_net_profit,
        
        -- Recency score: Lower recency_days = higher score (4)
        NTILE(4) OVER (ORDER BY recency_days DESC) AS r_score,
        
        -- Frequency score: Higher frequency_orders = higher score (4)
        NTILE(4) OVER (ORDER BY frequency_orders ASC) AS f_score,
        
        -- Monetary score: Higher monetary_net_revenue = higher score (4)
        NTILE(4) OVER (ORDER BY monetary_net_revenue ASC) AS m_score
    FROM rfm_raw
),

-- Step 3: Compute composite RFM scores and string representation
rfm_scores AS (
    SELECT 
        customer_id,
        customer_name,
        region,
        original_tier,
        recency_days,
        frequency_orders,
        monetary_net_revenue,
        monetary_net_profit,
        r_score,
        f_score,
        m_score,
        (CAST(r_score AS TEXT) || CAST(f_score AS TEXT) || CAST(m_score AS TEXT)) AS rfm_cell,
        (r_score + f_score + m_score) AS rfm_composite_score
    FROM rfm_quartiles
),

-- Step 4: Map RFM scores into business segments
rfm_segmented AS (
    SELECT 
        customer_id,
        customer_name,
        region,
        recency_days,
        frequency_orders,
        monetary_net_revenue,
        monetary_net_profit,
        r_score,
        f_score,
        m_score,
        rfm_cell,
        rfm_composite_score,
        CASE 
            WHEN r_score >= 3 AND f_score >= 3 AND m_score >= 3 THEN 'Champions'
            WHEN r_score >= 3 AND f_score >= 2 AND m_score >= 2 THEN 'Loyal Customers'
            WHEN r_score >= 3 AND f_score <= 2 THEN 'Promising / Recent'
            WHEN r_score <= 2 AND f_score >= 3 AND m_score >= 3 THEN 'At-Risk (High Value)'
            WHEN r_score <= 2 AND f_score <= 2 AND m_score <= 2 THEN 'Lost / Inactive'
            ELSE 'Needs Attention'
        END AS rfm_segment
    FROM rfm_scores
)

-- Step 5: Final Executive Aggregation by Segment
SELECT 
    rfm_segment,
    COUNT(customer_id) AS total_customers,
    ROUND((COUNT(customer_id) * 100.0) / (SELECT COUNT(*) FROM rfm_segmented), 2) AS customer_share_pct,
    ROUND(AVG(recency_days), 1) AS avg_recency_days,
    ROUND(AVG(frequency_orders), 1) AS avg_frequency_orders,
    ROUND(AVG(monetary_net_revenue), 2) AS avg_monetary_net_revenue,
    ROUND(SUM(monetary_net_revenue), 2) AS total_segment_net_revenue,
    ROUND(SUM(monetary_net_profit), 2) AS total_segment_net_profit,
    ROUND((SUM(monetary_net_profit) / NULLIF(SUM(monetary_net_revenue), 0)) * 100.0, 2) AS segment_profit_margin_pct
FROM rfm_segmented
GROUP BY rfm_segment
ORDER BY total_segment_net_revenue DESC;
